<?php require_once "menu.php"?>
        <article>
            <header>
            <h1>Introdução</h1>
            </header>
            
                <p>A fabricação de componentes para a indústria automotiva a partir de chapas de aços envolve operações consecutivas ou sobrepostas de corte, flexão, alongamento e expansão de furos. Neste aspecto, os aços produzidos por composição química e processos termomecânicos adequados, atendem as demandas que essas operações solicitam.</p><p>Ao longo das últimas décadas, os projetistas de automóveis utilizaram métodos modernos de fabricação de componentes para a indústria automotiva a partir de chapas que melhoraram a segurança dos veículos ao usar classes de aço com maior resistência e conformação. Estes são utilizados para fabricar para-choques, suportes transversais e laterais, soleiras de portas e arcos de teto, para que possam absorver o máximo de energia cinética possível por deformação em caso de colisão.</p><p>Na produção destas peças de veículos é de vital importância que a conformação é usada para fabricar essas peças seja responsável de assegurar que o aço funcionará de uma maneira confiável e previsível. Como o processo de expandir furos é amplamente utilizado na indústria automotiva durante operações de conformação de chapas metálicas, um método comum de se analisar o processo é o chamado ensaio de "expansão de furos".</p><p>É um procedimento estabelecido na norma ISO 16630 (2017). Especificamente, a norma descreve um método para determinar a taxa de expansão de furos em chapas e tiras metálicas com faixa de espessura entre 1,2 e 6,0 mm e largura de pelo menos 90,0mm. O teste é aplicável a chapas metálicas e é usado para avaliar a adequação do produto para a formação de flanges.</p><p>Antes que um teste possa ser conduzido, uma amostra de chapa deve ser fabricada. Em seguida, um orifício com 10,0mm de diâmetro é perfurado em uma amostra de chapa fina. Depois de inserir a amostra de chapa metálica em uma máquina de teste, um mandril de aço em formato cônico é forçado para o centro do furo previamente perfurado a partir de baixo na direção em que foi originalmente perfurado. O orifício então se expande até que as trincas comecem a se formar na borda interna do orifício perfurado que foi criado com o mandril.</p><p>Convencionalmente, a formação de fissuras na borda da amostra seria monitorada por um operador que observaria a amostra de cima e pararia a máquina de teste manualmente assim que as trincas começassem a se formar. Porém já existem métodos que fazem a menção da câmera como fundamental, para uma melhor visualização do resultado real mostrado. O diâmetro do orifício interno na amostra seria então medido com um paquímetro.</p><p>Neste contexto, o teste expansão de furo é desenvolvido e aplicado a diferentes aços. Alta resistência, relacionando os resultados obtidos com a química dos aços, suas propriedades mecânicas gerais e suas estruturas metalográficas. Desta forma, é possível ter uma importante ferramenta para auxiliar o usuário nos casos que envolvem esta operação específica.</p>
            
            <header>
            <h1>Ensaio de Expansão de Furo</h1>
            </header>
            
                <p>Expansão de furo é um teste simulado para estudar o alongamento das arestas cortadas. Embora também, a resposta do material da chapa e as condições da borda do furo são mecanismos que significativamente pode afetar o resultado do teste que é previsto por norma ISO 16630 (2017). Por um lado, o teste pode ser empregado para a otimização do corte com tecnologias como (por exemplo, eletroerosão, corte a laser, etc.) para um determinado material alcançar o mais alto grau de alongamento em operações de formação subsequentes.</p>
                <p>Por outro lado, é adequado para a seleção do material (determinadas operações de corte e conformação) o desenvolvimento de tolerâncias a danos materiais em relação ao flangeamento por estiramento. Dentro nos últimos anos tem aumentado significativamente, o número de testes de expansão de furo que tem seguido de acordo com a norma ISO 16630 (2017) que fez a padronização de tudo, porém não do método em si.</p>
                <p>A conformação de chapas pode ser dividida em conformação do corpo e borda da chapa. Pode ser descrita como a capacidade de o corpo de prova poder ser deformado em uma peça sem defeito devido à ductilidade. Esta propriedade pode ser determinada pela formação de curva limite, onde são usados em experimentos de estampagem profunda e medidas de ductilidade em testes de tração convencionais, que mostrará quando passará a deformar a borda onde está localizado o furo.</p>
                <p>Sua medição para o ensaio é conhecida como taxa de expansão de furo <i>(HER – Hole Expansion Ratio)</i>. Para minimizar o esforço experimental necessário, parece razoável desenvolver um método mais eficiente método de teste e dar uma olhada crítica na confiabilidade do limite da taxa de expansão do furo (de acordo com a norma citada acima) como parâmetro característico, avaliando o alongamento da borda. Esta contribuição apresenta um método alternativo para ensaios e avaliação, permitindo uso ainda mais eficientes e confiáveis, possibilitando avaliação dinâmica dos resultados do teste.</p>
            
                <figure id="img_centro">
                    <img class="img1" src="../_img/ensaio_equacao.PNG">
                </figure>
                <figcaption><b>Figura 1.</b> Visão esquemática do teste e a relação da expansão de furo (λ) obtida.</figcaption>
            </article>
<?php require_once "footer.php"?>